name: printful
description: "A Flutter plugin for seamless integration with the Printful API.
Manage products, orders, shipping rates, and tracking directly in your Flutter apps with native Android & iOS support.
Perfect for building custom e-commerce, print-on-demand, or dropshipping solutions."
version: 1.0.6
homepage: https://github.com/minhto2811/printful.git


environment:
  sdk: ^3.7.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  retrofit: ^4.6.0
  logger: ^2.6.0
  json_annotation: ^4.9.0
  get_it: ^8.2.0
  flutter_web_auth_2: ^5.0.0-alpha.3
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  retrofit_generator: ^9.7.0
  build_runner: ^2.5.4
  json_serializable: ^6.9.4


flutter:
